title: ELLIS Life Heidelberg
email: nambirajan.govindarajan@dkfz-heidelberg.de
description: >-
  ELLIS Life Heidelberg Unit Website.
baseurl: ""
url: "https://ellis-life-heidelberg.eu/"
sass:
    sass_dir: _sass
sass:
    style: compressed